// See https://aka.ms/new-console-template for more information
string GRUL = "Gru";
string GRUU = "GRU";
string AGNESL = "Agnes";
string AGNESU = "AGNES";
string EDITHL = "Edith";
string EDITHU = "EDITH";
string MARGOL = "Margo";
string MARGOU = "MARGO";
string THEVENDOR = "The vender";
string VENDOR = "VENDOR";

Console.WriteLine(AGNESU + " (O.S.)");
    Console.WriteLine("\"Oh my gosh look at that fluffy unicorn!\"\n");
    Console.WriteLine("A FLUFFY UNICORN");
Console.WriteLine("is the main prize at the shooting gallery.\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"He's so fluffy I'm gonna die!!!\"\n");
Console.WriteLine(MARGOU);
Console.WriteLine("\"You gotta let us play for it.\"\n");
Console.WriteLine(GRUU);
Console.WriteLine("\"No, no, no\"\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"Come on!\"\n");
Console.WriteLine(GRUL + " sighs and addresses the slimy " + VENDOR + "\n");
Console.WriteLine(GRUU);
    Console.WriteLine("\"How much for the fluffy unicorn?\"\n");
Console.WriteLine(VENDOR);
Console.WriteLine("(chuckles) \"Well...it is not for sale. But all you gotta do to win it is knock down that little spaceship there.\"\n");
Console.WriteLine(THEVENDOR + " points to the smallest of the spaceship targets.\n");
Console.WriteLine(VENDOR);
Console.WriteLine("\"It's easy!\"\n");
Console.WriteLine(GRUU + " nods. He slaps a dollar bill on the table. " + THEVENDOR + " slurps on his drink, and presses a button that opens the curtains and readies the cork guns.\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"Yay!\"\n");
Console.WriteLine("They take aim and open fire! POP! POP! POP! They all miss.\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"Again!\"\n");
Console.WriteLine(MARGOU);
Console.WriteLine("\"Wait!\"\n");
Console.WriteLine(EDITHU);
Console.WriteLine("\"Ah come on. One more time\"\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"Just one more! I accidentally closed my eyes!\"\n");
Console.WriteLine(GRUU + " slaps down another bill. POP! POP! POP! This time " + AGNESL + "\'s cork hit the target.\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"I hit it, I hit it! Did you see that? I hit it!\"\n");
Console.WriteLine("The video sign above the game reads: \"YOU LOSE.\"" + GRUL + " reacts.\n");
Console.WriteLine(EDITHU);
Console.WriteLine("\"Awww.\"\n");
Console.WriteLine(GRUU);
Console.WriteLine("\"Whoa, whoa, whoa...What was that? She hit that! I saw that with my own eyes!\"\n");
Console.WriteLine(THEVENDOR + " gives " + GRUL + " asmarmy smile. He flips through a stack of dollar bills.\n");
Console.WriteLine(VENDOR);
Console.WriteLine("\"Hey, buddy. Let me explain something to you.\"\n");
Console.WriteLine(THEVENDOR + " points to the back of the range.\n");
Console.WriteLine(VENDOR);
Console.WriteLine("\"Ya see that little tin spaceship? You see how it's not knocked over? Do you know what that means, professor?\"\n");
Console.WriteLine(THEVENDOR + " leans over the counter and gets right in " + GRUL + "\'s face.\n");
Console.WriteLine(VENDOR);
Console.WriteLine("\"It means you DON\'T GET THE UNICORN! Someone\'s got a frowny face. Better luck next time!\"\n");
Console.WriteLine(GRUL + " stares at " + THEVENDOR + ", his blood beginning to boil. He remains calm and smiles at " + THEVENDOR + "\n");
Console.WriteLine(GRUU);
Console.WriteLine("\"Okay, my turn.\"\n");
Console.WriteLine(GRUL + " calmly reaches into his coat and pulls out a small gun that transforms into an enormous RAY GUN. BLAM! A bright blue RAY BLAST connects with the back of the shooting range, leaving no sign of the targets, just a giant gaping hole. " + GRUL + " turns to " + THEVENDOR + "\n");
Console.WriteLine(GRUU);
Console.WriteLine("\"Knocked over.\"\n");
Console.WriteLine(THEVENDOR + " trembles, silenced. " + GRUL + "pockets his weapon and grabs the unicorn. He hands it to\n");
Console.WriteLine(AGNESU + ", " + MARGOU + ", and" + EDITHU);
Console.WriteLine("cheer and " + AGNESL + " hugs the animal tightly.\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"IT\'S SO FLUFFY!\"\n");
Console.WriteLine(MARGOU);
Console.WriteLine("\"That was awesome!\"\n");
Console.WriteLine(EDITHU);
Console.WriteLine("\"You blew up the whole thing!\"\n");
Console.WriteLine(AGNESU);
Console.WriteLine("\"Let\'s go destroy another game!\"\n");
Console.WriteLine("And then it happens: actually connecting with the girls and enjoying being with them, " + GRUL + " allows a small smile to creep across his face");
